name: export-and-branch-solution
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:
  inputs:
      solution_name:
        description: 'Name of the solution from Power Platform'
        required: true
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1
      ENVIRONMENT_URL: 'https://rajadev.crm8.dynamics.com/'
      CLIENT_ID: '0a00a0cd-ed0b-4b09-935f-d0a579aa8e11'
      TENANT_ID: '21f74bf9-8ab8-4168-811d-fa04d78ab412'

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.POWERPLATFORMALM }}
        tenant-id: ${{env.TENANT_ID}}

    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: 'https://rajadev.crm8.dynamics.com'
        client-secret: ${{ secrets.POWERPLATFORMALM }}
        tenant-id: ${{env.TENANT_ID}}
        app-id: ${{env.CLIENT_ID}}
        solution-name: ${{ github.event.inputs.solution_name }}
        solution-output-file: out/exported/${{ github.event.inputs.solution_name }}.zip

    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: out/exported/${{ github.event.inputs.solution_name }}.zip
        solution-folder: out/solutions/${{ github.event.inputs.solution_name }}
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: out/solutions/${{ github.event.inputs.solution_name }}
        solution-target-folder: solutions/${{ github.event.inputs.solution_name }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true
