name: import-solution

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'Name of the solution to be imported'
        required: true
      environment_url:
        description: 'https://rajatest.crm8.dynamics.com/'
        required: true

env:
  # Edit your values here
  CLIENT_ID: '0a00a0cd-ed0b-4b09-935f-d0a579aa8e11'
  TENANT_ID: '21f74bf9-8ab8-4168-811d-fa04d78ab412'
  solution_name: '${{ github.event.inputs.solution_name }}'
  solution-file: 'solutions/${{ github.event.inputs.solution_name }}.zip'     

permissions:
  contents: read

jobs:
  import-to-environment:
    runs-on: windows-latest
    # or you can say runs-on: ubuntu-latest  

    steps:
    - uses: actions/checkout@v2

    - name: Find solution file
      id: find_solution
      run: |
      
        # Find the file path based on the solution name provided
        $env:solution_name = "${{ github.event.inputs.solution_name }}"
        $solution_file_path = "/solutions/${env:solution_name}.zip"
        echo "Solution file path: $solution_file_path"
        #echo "::set-output name=solution_file_path::$solution_file_path"
        echo "SOLUTION_FILE_PATH=$solution_file_path" >> $GITHUB_ENV

    - name: import-solution action
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: ${{github.event.inputs.environment_url}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.POWERPLATFORMALM }}
        tenant-id: ${{env.TENANT_ID}}
        solution-file: ${{ steps['Find solution file'].outputs.solution_file_path }}
        #solution-file: ${{env.solution-file}}
