name: import-solution

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'Name of the solution from Power Platform'
        required: true
      solution_import_folder:
        description: 'Folder name where the solution to import is located *do not change*'
        required: true
        default: out/solutions/
      solution_target_folder: 
        description: 'Folder name in target environment for the imported solution *do not change*'
        required: true
        default: solutions/

jobs:
  import-to-target:
    runs-on: windows-latest
    # or you can say runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: import-solution action
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: 'https://rajatest.crm8.dynamics.com/'
        app-id: '0a00a0cd-ed0b-4b09-935f-d0a579aa8e11'
        client-secret: ${{ secrets.POWERPLATFORMALM }}
        tenant-id: '21f74bf9-8ab8-4168-811d-fa04d78ab412'
        solution-file: ${{ github.event.inputs.solution_import_folder}}/${{ github.event.inputs.solution_name }}/Other/Solution.xml
        target-folder: ${{ github.event.inputs.solution_target_folder}}
